DROP TABLE IF EXISTS Course;
CREATE TABLE Course
(
	id bigint auto_increment primary key, 
	abbrev char not null,	
	number int not null,
	long_course_title char,	
	course_title char,	
	desc varchar,
	course_college char not null,	
	course_branch int not null,
	lastATP int not null,
	firstATP int not null,
	grading_system int not null,	
	credit_control int not null,	
	min_qtr_credits float not null,
	max_qtr_credits float not null,
	max_credits float not null,
	approved_dt datetime,	
	changed_dt datetime,	
	dropped_dt datetime,	
	last_update_dt datetime,	
	sr_crs_dl_appr_dt datetime,
	deductible boolean not null,
	honors boolean not null,
	dup_enroll boolean not null,
	course_ts_omit boolean not null,
	course_cat_omit boolean not null,
	writing_crs boolean not null,
	english_comp boolean not null,
	qsr boolean not null,
	vis_lit_perf_arts boolean not null,	
	indiv_society boolean not null,
	natural_world boolean not null,
	diversity_crs boolean not null,
	hyphen_type int,
	prior_dept_abbr char,
	prior_course_num int,
	resp_curric_abbr char,
	resp_course_no int,
	revision bigint not null default 0
);